# Dependencies
markdown:         kramdown
highlighter:      rouge
plugins: [jekyll-paginate]

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Harmon
tagline:          'Where Craftsmanship Meets Code, Under the Open Sky'
description:      "In the blur between home and hardware, a dad and partner, fluent in code yet versed in the tactile. Drones that soar, 3D artifacts that challenge the expected, stitched together by skill and thread. Camping under stars, debugging life one campfire at a time."
url:              http://www.harmonwood.com
baseurl:          /

author:
  name:           'Harmon Wood'
  url:            https://www.harmonwood.com

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/harmonwood


# GitHub Pages configuration
repository:       harmonwood/harmon-wood-com
branch:           gh-pages
