version: '3.4'

services:

  harmon-wood-com:
    image: jekyll/jekyll:latest
    volumes:
      - .:/srv/jekyll
    ports:
      - "4000:4000"
    command: jekyll serve --watch --drafts --force_polling